# Generated by Django 3.1.5 on 2021-01-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarket', '0002_auto_20210121_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='user_id',
            new_name='user',
        ),
    ]
